name: Sit provisioning pipeline

on:
  push:
    branches:
      - main

jobs:  
  scan-terraform-config:
    runs-on: ubuntu-latest
    name: Scan Terraform with Checov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./sit/
          soft_fail: true
  provisioning:
    runs-on: ubuntu-latest
    needs: [scan-terraform-config]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: secret/data/kv/terraform-vars sit | TF_VARIABLES 

      - name: Create variables file
        run: echo $TF_VARIABLES > ./sit/secrets.tfvars

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.wip}}
          service_account: ${{ secrets.service_account }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "Test_pipeline"
        run: |
          cd sit/
          terraform init
          terraform validate 
          terraform plan 
          terraform apply -auto-approve -var-file=./secrets.tfvars