name: Vault secrets example

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            secret/data/test/webApp AWS_ID | AWS_ID ;
            secret/data/test/webApp AWS_KEY | AWS_KEY ;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ env.AWS_ID }}'
          aws-secret-access-key: '${{ env.AWS_KEY }}'
          aws-region: eu-west-3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "Test_pipeline"
        run: |
          cd infra/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve