name: Vault secrets example

on: [push]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            secret/data/test/webApp Name | NAME ;
            secret/data/test/webApp famName | FAMNAME ;

      - name: Use secrets as environment variables
        run: |
          echo $NAME
          echo $FAMNAME